# Generated by Django 6.0.3 on 2026-03-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_favorite_scene_remove_book_times_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.CharField(choices=[('tbr', 'TBR'), ('reading', 'Currently Reading'), ('read', 'Read')], default='tbr', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
