# Generated by Django 6.0.3 on 2026-03-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_status_book_shelf_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='shelf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='tropes',
            field=models.ManyToManyField(to='books.trope'),
        ),
    ]
