# Generated by Django 6.0.3 on 2026-03-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_notes_book_progress_alter_book_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_comfort',
            field=models.BooleanField(default=False),
        ),
    ]
