# Generated by Django 6.0.3 on 2026-03-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_is_comfort'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_released',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
