# Generated by Django 6.0.3 on 2026-03-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('read', 'Read'), ('tbr', 'To Be Read'), ('unreleased', 'Unreleased')], max_length=20)),
                ('times_read', models.IntegerField(default=0)),
                ('tropes', models.ManyToManyField(blank=True, to='books.trope')),
            ],
        ),
    ]
