# Generated by Django 6.0.3 on 2026-04-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('shelf', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('is_comfort', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_released', models.BooleanField(default=True)),
                ('tropes', models.ManyToManyField(to='books.trope')),
            ],
        ),
    ]
