# Generated by Django 6.0.3 on 2026-03-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorite_scene',
        ),
        migrations.RemoveField(
            model_name='book',
            name='times_read',
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('tbr', 'TBR'), ('unreleased', 'Unreleased')], max_length=20),
        ),
    ]
